[theme]
primaryColor = "#D97706"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[logger]
level = "info"

[client]
showErrorDetails = true

[server]
maxUploadSize = 200
headless = true
enableXsrfProtection = false
